import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {urlFor, sanityClient} from "../lib/sanity"
import Link from 'next/link'
import styled from 'styled-components'

const recipiesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`

export default function Home({recipes}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to My Kitchen!</h1>
      <StyledUl>
        {recipes?.length > 0 && recipes.map((recipe) => (
          <li key={recipe._id}>
            <Link href="/">
              <a>
                <img src={urlFor(recipe.mainImage).url()} alt="" />
                <span>{recipe.name}</span>
              </a>
            </Link>
          </li>
          ))}
      </StyledUl>
    </div>
  )
}

const StyledUl = styled.ul`

  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 40px;
  list-style: none;
  padding: 0;

  li{
    a{
      display: block;
      height: 100%;
      text-decoration: none;
      color: #444;
      font-size: 22px;

    }

    img{
      height: 300px;
      object-fit: cover;
      margin-bottom: 12px;
      border: 0.5px solid #444;
      display: block;
    }
  }

`

export async function getStaticProps(){
 const recipes = await sanityClient.fetch(recipiesQuery)
 return {props: {recipes}}
}